[package]
name = "sigpipe-repro"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "client"
path = "src/bin/client.rs"

[[bin]]
name = "server"
path = "src/bin/server.rs"


[dependencies]
libc = "0.2"
observability = { path = "/Users/scott.opell/dd/dd-source/libs/rust/observability" }